export const Players = [
  { id: "a9f2b4xk", name: "Rohit Sharma", role: "bastman" },
  { id: "m2p7l3qz", name: "Shubman Gill", role: "bastman" },
  { id: "v8d1k6so", name: "Virat Kohli", role: "bastman" },
  { id: "c3n9r5wl", name: "Shreyas Iyer", role: "bastman" },
  { id: "k7b6t0xe", name: "KL Rahul", role: "wicket-keeper" },
  { id: "e5z3f8mv", name: "Hardik Pandya", role: "all-rounder" },
  { id: "l1x0n2qe", name: "Ravindra Jadeja", role: "all-rounder" },
  { id: "z4m7s9kp", name: "Kuldeep Yadav", role: "bowler" },
  { id: "h6v3y2nt", name: "Jasprit Bumrah", role: "bowler" },
  { id: "p9c8r1wd", name: "Mohammed Siraj", role: "bowler" },
  { id: "t2k5l8yb", name: "Mohammed Shami", role: "bowler" },
  { id: "q8z1v4md", name: "Kane Williamson", role: "bastman" },
  { id: "a3p6r9bk", name: "Devon Conway", role: "wicket-keeper" },
  { id: "l7x2n0qs", name: "Daryl Mitchell", role: "all-rounder" },
  { id: "b4v9k2je", name: "Will Young", role: "bastman" },
  { id: "m5y3l1ft", name: "Glenn Phillips", role: "all-rounder" },
  { id: "x9d7s6co", name: "Mitchell Santner", role: "all-rounder" },
  { id: "z2k8w4ry", name: "Rachin Ravindra", role: "all-rounder" },
  { id: "d1t6p5xl", name: "Ish Sodhi", role: "bowler" },
  { id: "f0n2m8qw", name: "Trent Boult", role: "bowler" },
  { id: "n6r5j3yb", name: "Tim Southee", role: "bowler" },
  { id: "u7c0v9ez", name: "Lockie Ferguson", role: "bowler" },
];
